export enum EMAIL_TYPE {
  SSO_SEND_SIGNUP_ACCOUNT_OTP = 'SSO_SEND_SIGNUP_ACCOUNT_OTP',
  SSO_INFORM_SIGNUP_ACCOUNT_INFO = 'SSO_INFORM_SIGNUP_ACCOUNT_INFO',
  SSO_SEND_RESET_PASSWORD_OTP = 'SSO_SEND_RESET_PASSWORD_OTP',
  SSO_INFORM_CHANGE_PASSWORD_INFO = 'SSO_INFORM_CHANGE_PASSWORD_INFO',
  SSO_SEND_WELCOME_ACCOUNT_INFO = 'SSO_SEND_WELCOME_ACCOUNT_INFO',
  SSO_INFORM_CHANGE_ACCOUNT_INFO = 'SSO_INFORM_CHANGE_ACCOUNT_INFO',
  SSO_INFORM_SETUP_ACCOUNT_INFO = 'SSO_INFORM_SETUP_ACCOUNT_INFO'
}
