import type { ObjectId } from 'mongodb'

import type { EncryptedPayload } from '../../acore/crypto'

export const SECRETS_COLLECTION = 'secrets'

export type SecretType = 'db' | 'api' | 'file'

/** Persistence shape (mirrors P002 §5.6). Always retrieved with `_id` populated. */
export interface SecretDoc {
  _id: ObjectId
  name: string
  type: SecretType
  encrypted: EncryptedPayload
  createdAt: Date
  updatedAt: Date
  createdBy: string
}

/** Document fields supplied at insert time. `_id` is generated by Mongo. */
export type SecretInsert = Omit<SecretDoc, '_id'>

/** Public-safe view used by admin endpoints. Never includes plaintext or ciphertext. */
export interface SecretSummary {
  id: string
  name: string
  type: SecretType
  keyVersion: number
  createdAt: Date
  updatedAt: Date
  createdBy: string
}
