import { makeAutoObservable } from 'mobx'
import { readJson, writeJson } from '@/acore/storage'

export type Doc = {
  id: string
  title: string
  source: string
  updatedAt: number
}

const STORAGE_KEY = 'ax-documents'

function isDoc(v: unknown): v is Doc {
  if (typeof v !== 'object' || v === null) return false
  const d = v as Record<string, unknown>
  return typeof d.id === 'string' && typeof d.title === 'string' && typeof d.source === 'string' && typeof d.updatedAt === 'number'
}

function isDocArray(v: unknown): v is Doc[] {
  return Array.isArray(v) && v.every(isDoc)
}

// Mock doc with both block kinds exercised so the view page proves end-to-end.
// Mốc 3 adds an edit flow that mutates `source` via setSource() and persists.
const DEMO_DOC: Doc = {
  id: 'demo',
  title: 'Q1 status report',
  source: `# Q1 status report

This snapshot was generated by the AI agent on **2026-05-15**. It bundles a status table and a velocity chart inline — the reader views, the editor reopens each block for tweaks.

## Tasks by status

\`\`\`ax-table
{
  "id": "tbl-status",
  "columns": [
    { "key": "owner", "title": "Owner", "kind": "string", "sortable": true },
    { "key": "open", "title": "Open", "kind": "number", "sortable": true },
    { "key": "inprogress", "title": "In progress", "kind": "number", "sortable": true },
    { "key": "done", "title": "Done", "kind": "number", "sortable": true }
  ],
  "data": [
    { "owner": "Alice", "open": 3, "inprogress": 5, "done": 12 },
    { "owner": "Bob", "open": 7, "inprogress": 2, "done": 9 },
    { "owner": "Carol", "open": 1, "inprogress": 4, "done": 18 },
    { "owner": "Dan", "open": 4, "inprogress": 3, "done": 7 }
  ]
}
\`\`\`

## Velocity (closed per week)

\`\`\`ax-chart
{
  "id": "cht-velocity",
  "option": {
    "title": { "text": "Tasks closed per week", "left": "center" },
    "tooltip": { "trigger": "axis" },
    "xAxis": { "type": "category", "data": ["W1", "W2", "W3", "W4", "W5", "W6"] },
    "yAxis": { "type": "value" },
    "series": [
      { "name": "closed", "type": "bar", "data": [12, 18, 9, 21, 17, 25] }
    ]
  }
}
\`\`\`

## Notes

- GFM features should still work: **bold**, *italic*, ~~strikethrough~~
- Plain code blocks render as code, not widgets:

\`\`\`ts
const greeting: string = 'hello'
\`\`\`
`,
  updatedAt: Date.now(),
}

export class DocumentStore {
  // Hydrate from localStorage if a valid persisted array exists; otherwise
  // start with the seed doc so the demo URL /docs/demo always works.
  docs: Doc[] = readJson(STORAGE_KEY, isDocArray) ?? [DEMO_DOC]

  constructor() {
    makeAutoObservable(this)
  }

  getById(id: string): Doc | undefined {
    return this.docs.find((d) => d.id === id)
  }

  setSource(id: string, source: string) {
    const doc = this.getById(id)
    if (!doc) return
    doc.source = source
    doc.updatedAt = Date.now()
    writeJson(STORAGE_KEY, this.docs)
  }
}
